# CMake generated Testfile for 
# Source directory: /lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI
# Build directory: /lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(global_T62 "regression_driver.sh" "global_T62" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_T62 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_T62_ozonly "regression_driver.sh" "global_T62_ozonly" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_T62_ozonly PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_4dvar_T62 "regression_driver.sh" "global_4dvar_T62" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_4dvar_T62 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_4denvar_T126 "regression_driver.sh" "global_4denvar_T126" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_4denvar_T126 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_fv3_4denvar_T126 "regression_driver.sh" "global_fv3_4denvar_T126" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_fv3_4denvar_T126 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_fv3_4denvar_C192 "regression_driver.sh" "global_fv3_4denvar_C192" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_fv3_4denvar_C192 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_lanczos_T62 "regression_driver.sh" "global_lanczos_T62" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_lanczos_T62 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(arw_netcdf "regression_driver.sh" "arw_netcdf" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(arw_netcdf PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(
          arw_binary "regression_driver.sh" "
          arw_binary" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(
          arw_binary PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(nmm_binary "regression_driver.sh" "nmm_binary" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(nmm_binary PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(nmm_netcdf "regression_driver.sh" "nmm_netcdf" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(nmm_netcdf PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(nmmb_nems_4denvar "regression_driver.sh" "nmmb_nems_4denvar" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(nmmb_nems_4denvar PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(hwrf_nmm_d2 "regression_driver.sh" "hwrf_nmm_d2" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(hwrf_nmm_d2 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(hwrf_nmm_d3 "regression_driver.sh" "hwrf_nmm_d3" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(hwrf_nmm_d3 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(rtma "regression_driver.sh" "rtma" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(rtma PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_enkf_T62 "regression_driver.sh" "global_enkf_T62" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_enkf_T62 PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(netcdf_fv3_regional "regression_driver.sh" "netcdf_fv3_regional" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(netcdf_fv3_regional PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_C96_fv3aero "regression_driver.sh" "global_C96_fv3aero" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_C96_fv3aero PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
add_test(global_C96_fv3aerorad "regression_driver.sh" "global_C96_fv3aerorad" "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/build")
set_tests_properties(global_C96_fv3aerorad PROPERTIES  TIMEOUT "86400" WORKING_DIRECTORY "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/regression" _BACKTRACE_TRIPLES "/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;319;add_test;/lfs/h1/ops/para/packages/nam.v4.2.0/sorc/nam_gsi.fd/GSI/CMakeLists.txt;0;")
subdirs("libsrc/wrflib")
subdirs("src/ncdiag")
subdirs("src/fv3gfs_ncio")
subdirs("src/gsi")
