#!/bin/ksh

#BSUB -oo out.nemsinterp_6
#BSUB -eo out.nemsinterp_6
#BSUB -n 4
#BSUB -J nemsinterp_6
#BSUB -W 00:30
#BSUB -P NAM-T2O
#BSUB -q "dev2"
#BSUB -R span[ptile=4] -R affinity[core]
#BSUB -x
#BSUB -a poe

export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Script name:         exhiresw_nemsinterp.sh.sms
# Script description:  Runs nemsinterp for NMMB
#
# Author:        Eric Rogers       Org: NP22         Date: 2004-07-02
#
# Abstract: The scripts runs the final pieces of the NMMB prelim job, with nemsinterp run to generate
#           model initial and boundary conditions.  Non-Guam domains have their land states updated
#           from the NAM using the coldstart program
#
# Script history log:
# 2003-11-01  Matt Pyle - Original script for parallel
# 2004-07-02  Eric Rogers - Preliminary modifications for production.
# 2004-10-01  Eric Rogers - Modified to run special real executable for Alaska NMM
# 2007-04-09  Matthew Pyle - Modified to run WPS rather than wrfsi
# 2009-09-24  Shawna Cokley - Streamlines way script obtains date information -
#                             pulls from $PDY rather than copying a file to the working directory
# 2013-10-30  Matthew Pyle - Breaks out last piece from old prelim script 

set -x

mkdir -p /stmpp2/Eric.Rogers/testnps_origcode
mkdir -p /stmpp2/Eric.Rogers/testnps_origcode/run_nemsinterp
cd /stmpp2/Eric.Rogers/testnps_origcode
export DATA=/stmpp2/Eric.Rogers/testnps_origcode

NDATE=/nwprod/util/exec/ndate

COMOUT=/stmpp2/Eric.Rogers/testnps_origcode/run_nemsinterp

LENGTH=84

PDY=20161220
cyc=12

yy=`echo $PDY | cut -c1-4`
mm=`echo $PDY | cut -c5-6`
dd=`echo $PDY | cut -c7-8`

ystart=`echo $PDY | cut -c1-4`
mstart=`echo $PDY | cut -c5-6`
dstart=`echo $PDY | cut -c7-8`

start=$ystart$mstart$dstart$cyc

int1=`$NDATE +12 $start`
yyint1=`echo $int1 | cut -c1-4`
mmint1=`echo $int1 | cut -c5-6`
ddint1=`echo $int1 | cut -c7-8`
hhint1=`echo $int1 | cut -c9-10`

int2=`$NDATE +12 $int1`
yyint2=`echo $int2 | cut -c1-4`
mmint2=`echo $int2 | cut -c5-6`
ddint2=`echo $int2 | cut -c7-8`
hhint2=`echo $int2 | cut -c9-10`

int3=`$NDATE +12 $int2`
yyint3=`echo $int3 | cut -c1-4`
mmint3=`echo $int3 | cut -c5-6`
ddint3=`echo $int3 | cut -c7-8`
hhint3=`echo $int3 | cut -c9-10`

int4=`$NDATE +12 $int3`
yyint4=`echo $int4 | cut -c1-4`
mmint4=`echo $int4 | cut -c5-6`
ddint4=`echo $int4 | cut -c7-8`
hhint4=`echo $int4 | cut -c9-10`

int5=`$NDATE +12 $int4`
yyint5=`echo $int5 | cut -c1-4`
mmint5=`echo $int5 | cut -c5-6`
ddint5=`echo $int5 | cut -c7-8`
hhint5=`echo $int5 | cut -c9-10`

int6=`$NDATE +12 $int5`
yyint6=`echo $int6 | cut -c1-4`
mmint6=`echo $int6 | cut -c5-6`
ddint6=`echo $int6 | cut -c7-8`
hhint6=`echo $int6 | cut -c9-10`

end=`$NDATE $LENGTH $start`

yend=`echo $end | cut -c1-4`
mend=`echo $end | cut -c5-6`
dend=`echo $end | cut -c7-8`

export CYCLE=$PDY$cyc

#########################################################
# RUN NEMSINTERP PROGRAM to generate input/boco files (NMMB)
#########################################################

cd $DATA

cycstart=`echo ${PDY}${cyc}`

start=$ystart$mstart$dstart

end=`$NDATE $LENGTH $cycstart`

yend=`echo $end | cut -c1-4`
mend=`echo $end | cut -c5-6`
dend=`echo $end | cut -c7-8`
hend=`echo $end | cut -c9-10`

### number of input levels depends on source model data

NUMLEVS=27

export MP_PGMMODEL=spmd
unset MP_CMDFILE

export PARMnam=/meso/save/Eric.Rogers/nam.v4.1.5/parm
export PARMnps=/meso/save/Eric.Rogers/tempscripts
export FIXnam=/meso/save/Eric.Rogers/nam.v4.1.5/fix
export EXECnam=/meso/save/Eric.Rogers/nam.v4.1.5/exec
export USHnps=/meso/save/Eric.Rogers/tempscripts

export INPUT_DATA=$DATA/run_metgrid

echo NEED TO RUN NEMSINTERP

mkdir -p $DATA/run_nemsinterp_6
cd $DATA/run_nemsinterp_6

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint5: | sed s:MSTART:$mmint5: \
 | sed s:DSTART:$ddint5: | sed s:HSTART:$hhint5: | sed s:YEND:$yyint6: \
 | sed s:MEND:$mmint6:   | sed s:DEND:$ddint6: | sed s:HEND:$hhint6:g > $DATA/run_nemsinterp_6/namelist.nps

yy1=`echo $int5 | cut -c1-4`
mm1=`echo $int5 | cut -c5-6`
dd1=`echo $int5 | cut -c7-8`
hh1=`echo $int5 | cut -c9-10`

cp $INPUT_DATA/nam.t${cyc}z.met_nmb.d01.${yy1}-${mm1}-${dd1}_${hh1}:00:00.dio met_nmb.d01.${yy1}-${mm1}-${dd1}_${hh1}:00:00.dio

t2=`$NDATE +3 $int5`

yy2=`echo $t2 | cut -c1-4`
mm2=`echo $t2 | cut -c5-6`
dd2=`echo $t2 | cut -c7-8`
hh2=`echo $t2 | cut -c9-10`

cp $INPUT_DATA/nam.t${cyc}z.met_nmb.d01.${yy2}-${mm2}-${dd2}_${hh2}:00:00.dio met_nmb.d01.${yy2}-${mm2}-${dd2}_${hh2}:00:00.dio

t3=`$NDATE +3 $t2`

yy3=`echo $t3 | cut -c1-4`
mm3=`echo $t3 | cut -c5-6`
dd3=`echo $t3 | cut -c7-8`
hh3=`echo $t3 | cut -c9-10`

cp $INPUT_DATA/nam.t${cyc}z.met_nmb.d01.${yy3}-${mm3}-${dd3}_${hh3}:00:00.dio met_nmb.d01.${yy3}-${mm3}-${dd3}_${hh3}:00:00.dio

t4=`$NDATE +3 $t3`

yy4=`echo $t4 | cut -c1-4`
mm4=`echo $t4 | cut -c5-6`
dd4=`echo $t4 | cut -c7-8`
hh4=`echo $t4 | cut -c9-10`

cp $INPUT_DATA/nam.t${cyc}z.met_nmb.d01.${yy4}-${mm4}-${dd4}_${hh4}:00:00.dio met_nmb.d01.${yy4}-${mm4}-${dd4}_${hh4}:00:00.dio

t5=`$NDATE +3 $t4`

yy5=`echo $t5 | cut -c1-4`
mm5=`echo $t5 | cut -c5-6`
dd5=`echo $t5 | cut -c7-8`
hh5=`echo $t5 | cut -c9-10`

cp $INPUT_DATA/nam.t${cyc}z.met_nmb.d01.${yy5}-${mm5}-${dd5}_${hh5}:00:00.dio met_nmb.d01.${yy5}-${mm5}-${dd5}_${hh5}:00:00.dio

EXECnps=/meso/save/Eric.Rogers/nam_gfs2017q3/sorc/nam_nps_bocos.fd/NMMB_init/NPS

. /usrx/local/Modules/default/init/ksh
###module switch ics ics/15.0.3
module load NetCDF/4.2/serial

##export pgm=hiresw_nemsinterp
cp $EXECnps/nemsinterp.exe .
mpirun.lsf ./nemsinterp.exe
##export err=$?; err_chk

cp boco.0000 $COMOUT/nam.t${cyc}z.boco.0060
cp boco.0003 $COMOUT/nam.t${cyc}z.boco.0063
cp boco.0006 $COMOUT/nam.t${cyc}z.boco.0066
cp boco.0009 $COMOUT/nam.t${cyc}z.boco.0069

echo "DONE" > ../nemsinterpdone6

cd $DATA

##while [ $count -lt 16 ]
##do
##sleep 20
##count=`ls $COMOUT/hiresw.t${cyc}z.${NEST}${MODEL}.boco.* | wc -l`
##echo now see $count boco files in com
##done

