#!/bin/ksh

#BSUB -oo out.nps
#BSUB -eo out.nps
#BSUB -n 7
#BSUB -J ndas_coldstart_prep_18
#BSUB -W 00:10
#BSUB -P NAM-T2O
#BSUB -q "debug"
#BSUB -R span[ptile=7]
#BSUB -R "affinity[core]"
#BSUB -R rusage[mem=4000]
#####BSUB -x
## BSUB -a poe

export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes

. /usrx/local/prod/lmod/lmod/init/ksh
module load prod_util/1.1.0
module load NetCDF/4.5.0
module load lsf/10.1
module load ips/18.0.1.163
module load impi/18.0.1
module load CFP/2.0.1

set -x

# NDATE=/nwprod/util/exec/ndate

BASE=/gpfs/dell2/ptmp/Matthew.Pyle

mkdir -p ${BASE}/testnps_origcode
mkdir -p ${BASE}/testnps_origcode/run_ungrib
cd ${BASE}/testnps_origcode
export DATA=${BASE}/testnps_origcode

INPUT=/gpfs/dell1/nco/ops/com/gfs/para/gfs.20190117/06

export mod=AVN

# grab fhrs 6-93 to get six groups of five GFS files
LENGTH=87

export jlogfile=~/jlog

export cyc=12

export DOMNAM=nam

GFSDATE=2019011706
cycgfs=06
CYCLE=2019011712
PDY=20190117
# INPUT=/meso/noscrub/Eric.Rogers/gfspll.20190117
INPUT=/gpfs/dell1/nco/ops/com/gfs/para/gfs.20190117/06

export PARMnam=/gpfs/dell2/emc/modeling/noscrub/Eric.Rogers/nam.v4.1.10/parm
export PARMnps=$PARMnam
export FIXnam=/gpfs/dell2/emc/modeling/noscrub/Eric.Rogers/nam.v4.1.10/fix
export USHnam=/gpfs/dell2/emc/modeling/noscrub/Eric.Rogers/nam.v4.1.10/ush
export USHnps=/gpfs/dell2/emc/modeling/noscrub/Eric.Rogers/nam.v4.1.10/ush
# path to your binaries
###EXECnam=/meso/save/Eric.Rogers/nam.v4.1.5/exec/wcoss.exec
export EXECnam=/gpfs/dell2/emc/modeling/noscrub/Matthew.Pyle/nam_transition/nam_nps.fd/namtransition_exec

export pgmout=myout.log

mkdir -p $DATA/run_ungrib_1
mkdir -p $DATA/run_ungrib_2
mkdir -p $DATA/run_ungrib_3
mkdir -p $DATA/run_ungrib_4
mkdir -p $DATA/run_ungrib_5
mkdir -p $DATA/run_ungrib_6
mkdir -p $DATA/run_ungrib_7
mkdir -p $DATA/run_ungrib_8

mod=gfs
type=pgrb2.0p25.f0
suf=""

fhr=06

while [ $fhr -le 93 ] ; do
  cp $INPUT/${mod}.t${cycgfs}z.${type}${fhr} $DATA/.
  let "fhr=fhr+3"
  typeset -Z2 fhr
done

yy=`echo $PDY | cut -c1-4`
mm=`echo $PDY | cut -c5-6`
dd=`echo $PDY | cut -c7-8`

ystart=`echo $PDY | cut -c1-4`
mstart=`echo $PDY | cut -c5-6`
dstart=`echo $PDY | cut -c7-8`

start=$ystart$mstart$dstart$cyc

int1=`$NDATE +12 $start`
yyint1=`echo $int1 | cut -c1-4`
mmint1=`echo $int1 | cut -c5-6`
ddint1=`echo $int1 | cut -c7-8`
hhint1=`echo $int1 | cut -c9-10`

int2=`$NDATE +12 $int1`
yyint2=`echo $int2 | cut -c1-4`
mmint2=`echo $int2 | cut -c5-6`
ddint2=`echo $int2 | cut -c7-8`
hhint2=`echo $int2 | cut -c9-10`

int3=`$NDATE +12 $int2`
yyint3=`echo $int3 | cut -c1-4`
mmint3=`echo $int3 | cut -c5-6`
ddint3=`echo $int3 | cut -c7-8`
hhint3=`echo $int3 | cut -c9-10`

int4=`$NDATE +12 $int3`
yyint4=`echo $int4 | cut -c1-4`
mmint4=`echo $int4 | cut -c5-6`
ddint4=`echo $int4 | cut -c7-8`
hhint4=`echo $int4 | cut -c9-10`

int5=`$NDATE +12 $int4`
yyint5=`echo $int5 | cut -c1-4`
mmint5=`echo $int5 | cut -c5-6`
ddint5=`echo $int5 | cut -c7-8`
hhint5=`echo $int5 | cut -c9-10`

int6=`$NDATE +12 $int5`
yyint6=`echo $int6 | cut -c1-4`
mmint6=`echo $int6 | cut -c5-6`
ddint6=`echo $int6 | cut -c7-8`
hhint6=`echo $int6 | cut -c9-10`

int7=`$NDATE +12 $int6`
yyint7=`echo $int7 | cut -c1-4`
mmint7=`echo $int7 | cut -c5-6`
ddint7=`echo $int7 | cut -c7-8`
hhint7=`echo $int7 | cut -c9-10`

end=`$NDATE $LENGTH $start`

yend=`echo $end | cut -c1-4`
mend=`echo $end | cut -c5-6`
dend=`echo $end | cut -c7-8`

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$ystart: | sed s:MSTART:$mstart: \
 | sed s:DSTART:$dstart: | sed s:HSTART:$cyc: | sed s:YEND:$yyint1: \
 | sed s:MEND:$mmint1:   | sed s:DEND:$ddint1: | sed s:HEND:$hhint1: > $DATA/namelist.nps.1

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint1: | sed s:MSTART:$mmint1: \
 | sed s:DSTART:$ddint1: | sed s:HSTART:$hhint1: | sed s:YEND:$yyint2: \
 | sed s:MEND:$mmint2:   | sed s:DEND:$ddint2: | sed s:HEND:$hhint2: > $DATA/namelist.nps.2

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint2: | sed s:MSTART:$mmint2: \
 | sed s:DSTART:$ddint2: | sed s:HSTART:$hhint2: | sed s:YEND:$yyint3: \
 | sed s:MEND:$mmint3:   | sed s:DEND:$ddint3: | sed s:HEND:$hhint3: > $DATA/namelist.nps.3

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint3: | sed s:MSTART:$mmint3: \
 | sed s:DSTART:$ddint3: | sed s:HSTART:$hhint3: | sed s:YEND:$yyint4: \
 | sed s:MEND:$mmint4:   | sed s:DEND:$ddint4: | sed s:HEND:$hhint4: > $DATA/namelist.nps.4

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint4: | sed s:MSTART:$mmint4: \
 | sed s:DSTART:$ddint4: | sed s:HSTART:$hhint4: | sed s:YEND:$yyint5: \
 | sed s:MEND:$mmint5:   | sed s:DEND:$ddint5: | sed s:HEND:$hhint5: > $DATA/namelist.nps.5

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint5: | sed s:MSTART:$mmint5: \
 | sed s:DSTART:$ddint5: | sed s:HSTART:$hhint5: | sed s:YEND:$yyint6: \
 | sed s:MEND:$mmint6:   | sed s:DEND:$ddint6: | sed s:HEND:$hhint6: > $DATA/namelist.nps.6

cat $PARMnps/nam_namelist.nps_bocos | sed s:YSTART:$yyint6: | sed s:MSTART:$mmint6: \
 | sed s:DSTART:$ddint6: | sed s:HSTART:$hhint6: | sed s:YEND:$yyint7: \
 | sed s:MEND:$mmint7:   | sed s:DEND:$ddint7: | sed s:HEND:$hhint7: > $DATA/namelist.nps.7

#####

cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_1/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_2/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_3/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_4/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_5/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_6/Vtable
cp $PARMnps/nam_Vtable.GFS.bocos  $DATA/run_ungrib_7/Vtable

GRIBSRC=GFS

### Get the needed GRIB files into each of the six run_ungrib subdirectories

mv ${mod}.t${cycgfs}z.${type}06${suf} ./run_ungrib_1/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}09${suf} ./run_ungrib_1/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}12${suf} ./run_ungrib_1/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}15${suf} ./run_ungrib_1/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}18${suf} ./run_ungrib_1/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}18${suf} ./run_ungrib_2/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}21${suf} ./run_ungrib_2/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}24${suf} ./run_ungrib_2/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}27${suf} ./run_ungrib_2/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}30${suf} ./run_ungrib_2/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}30${suf} ./run_ungrib_3/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}33${suf} ./run_ungrib_3/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}36${suf} ./run_ungrib_3/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}39${suf} ./run_ungrib_3/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}42${suf} ./run_ungrib_3/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}42${suf} ./run_ungrib_4/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}45${suf} ./run_ungrib_4/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}48${suf} ./run_ungrib_4/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}51${suf} ./run_ungrib_4/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}54${suf} ./run_ungrib_4/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}54${suf} ./run_ungrib_5/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}57${suf} ./run_ungrib_5/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}60${suf} ./run_ungrib_5/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}63${suf} ./run_ungrib_5/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}66${suf} ./run_ungrib_5/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}66${suf} ./run_ungrib_6/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}69${suf} ./run_ungrib_6/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}72${suf} ./run_ungrib_6/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}75${suf} ./run_ungrib_6/GRIBFILE.AAD
cp ${mod}.t${cycgfs}z.${type}78${suf} ./run_ungrib_6/GRIBFILE.AAE

mv ${mod}.t${cycgfs}z.${type}78${suf} ./run_ungrib_7/GRIBFILE.AAA
mv ${mod}.t${cycgfs}z.${type}81${suf} ./run_ungrib_7/GRIBFILE.AAB
mv ${mod}.t${cycgfs}z.${type}84${suf} ./run_ungrib_7/GRIBFILE.AAC
mv ${mod}.t${cycgfs}z.${type}87${suf} ./run_ungrib_7/GRIBFILE.AAD
mv ${mod}.t${cycgfs}z.${type}90${suf} ./run_ungrib_7/GRIBFILE.AAE

### run_ungrib
cd $DATA

rm -rf poescript

echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 2" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 1" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 3" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 4" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 5" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 6" >> poescript
echo "$USHnps/nam_boco_ungrib_gen.sh $cyc 7" >> poescript

chmod 775 $DATA/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/poescript

# export pgm=nam_boco_ungrib_gen.sh
# mpirun -configfile $MP_CMDFILE

./poescript
###export err=$?; err_chk


