#!/bin/bash
set -xa

# export HOMEnam=$PACKAGEROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${jobid:?}


# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_prdgen.sh
jerr=$?
########################################################

echo "prdgen is done" > $FCSTDIR/prdgendone${fcsthrs}.${tmmark}

cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

exit $jerr
