#!/bin/sh
set -xa

export PS4='$SECONDS + '
date

# export HOMEnam=$PACKAGEROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${job}.${pid}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

export DATA=${DATAROOT}/${jobid:?}
mkdir $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export MACHID=${MACHID:-wcoss2}
export pid=$$
export pgmout="OUTPUT.${pid}"

export NET=nam
export RUN=nam
export model=nam
export cycle=t${cyc}z

################################
# Set up the HOME directory
################################
#### export HOMEnam=$PACKAGEROOT/nam.${nam_ver}
export EXECnam=$HOMEnam/exec
export FIXnam=$HOMEnam/fix
export PARMnam=$HOMEnam/parm
export USHnam=$HOMEnam/ush

###################################
# Set up the UTILITIES
###################################
export HOMEutil=$UTILSHAREDROOT
export EXECutil=$UTILSHAREDROOT/exec
export FIXutil=$FIXshared
export PARMutil=$HOMEnam/util/parm
export UTIL_EXECnam=${UTIL_EXECnam:-${HOMEnam}/util/exec}
export UTIL_USHnam=${UTIL_USHnam:-${HOMEnam}/util/ush}
export UTIL_PARMnam=${UTIL_PARMnam:-${HOMEnam}/util/parm}
export USHutil=$USHshared

##############################
# Define Special Variables
##############################

# Run setpdy and initialize PDY variables
sh setpdy.sh
. ./PDY

########################################
# Set up the input/output directory
########################################
# JY export COMIN=$COMROOT/nam/${nam_ver}/${RUN}.${PDY}
#export COMOUT=$COMROOT/nam/${nam_ver}/${RUN}.${PDY}
#export COMOUTwmo=$COMROOT/nam/${nam_ver}/${RUN}.${PDY}/wmo
export COMIN=${COMIN:-$(compath.py $envir/nam/$nam_ver)/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py $envir/nam/$nam_ver)/${RUN}.${PDY}}
export COMOUTwmo=${COMOUT}/wmo

mkdir -p $COMOUT $COMOUTwmo
env

########################################################
# Execute the script.
$HOMEnam/scripts/exnam_fbwind.sh
########################################################

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

date
