#!/bin/bash
set -xa

# export HOMEnam=$PACKAGEROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=nam_${cyc}_${tmmark}_${envir}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_postsnd.sh
jerr=$?
########################################################

cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

cd ${DATAROOT}
exit $jerr
