#!/bin/bash
set -xa

# export HOMEnam=$PACKAGEROOT/nam.${nam_ver}
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${jobid:?}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

  # Got these from the FV3GFS env.
  export MPI_LABELIO=YES
  export MP_STDOUTMODE="ORDERED"

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_postgoestb_nest.sh
jerr=$?
########################################################

cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

exit $jerr
